# Exported from Render on 2024-07-21T14:03:42Z
services:
- type: web
  name: blogpessoal
  runtime: docker
  repo: https://github.com/vmendesdev/blogpessoal
  plan: free
  envVars:
  - key: POSTGREUSER
    sync: false
  - key: POSTGRESPORT
    sync: false
  - key: POSTGRESPASSWORD
    sync: false
  - key: POSTGRESHOST
    sync: false
  - key: POSTGRESDATABASE
    sync: false
  region: oregon
  dockerContext: .
  dockerfilePath: ./Dockerfile
version: "1"
